paths:
  api/products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Add a new product
      requestBody:
        description: Product object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Product added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  api/products/{id}:
    get:
      summary: Get a product by ID
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Update a product
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      requestBody:
        description: Updated product object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Product not found
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          description: ID of the product
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
        title:
          type: string
        description:
          type: string
        code:
          type: number
        price:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: array
          items:
            type: string
        thumbnails:
          type: string
        createDate:
          type: number
    NewProduct:
      type: object
      properties:
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        code:
          type: number
          required: true
        price:
          type: number
          required: true
        status:
          type: boolean
          required: true
        stock:
          type: number
          required: true
        category:
          type: array
          required: true
          items:
            type: string
            required: true
        thumbnails:
          type: string  
          required: true